spring.config.import=optional:file:.env[.properties]
<<<<<<< HEAD
spring.application.name=rpg-manager
spring.datasource.url=jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
=======
google.client.id=${GOOGLE_CLIENT_ID}
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key
jwt.access.expires.in=${JWT_ACCESS_EXPIRES_IN}
jwt.refresh.expires.in=${JWT_REFRESH_EXPIRES_IN}
allowed.origins=http://localhost:4200

spring.application.name=rpg-manager
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
>>>>>>> desenvolvimento
